---
# tasks file for docker-setup

- name: Configuring yum for instalation of Docker
  yum_repository:
        name: Docker123
        description: Docker yum repo
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no

- name: Installing Docker only if not present
  shell: rpm -q docker-ce; if [ $? != 0 ]; then yum install docker-ce --nobest -y; fi 

- name: Starting Docker Services
  service:
        name: docker
        state: started
        enabled: yes        
